/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transsystem;

//import transsystem.GainesvilleTransportationSystem;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import transsystem.SearchResult;
import transsystem.SearchRoutesGUI;

/**
 *
 * @author Sabrina
 */
public class ResultsDetailGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResultsDetailGUI
     */
    private Carpool c=null;
    private Alert al=null;
    private int srid;
    
    public ResultsDetailGUI() {
        initComponents();   
    }

    public ResultsDetailGUI(int id,Alert al){
        this();
        this.srid=id;
        this.al=al;
        DefaultListModel m = (DefaultListModel)(jList1.getModel());
        m.clear();
        SearchResult result=TransSystem.getSearchResult(id); 
        String[] s=result.toString().split("\n");
        for(int i=0; i<s.length; i++){
            m.addElement(s[i]);
        }
        jButton3.setEnabled(false);
    }
    
    public ResultsDetailGUI(Carpool c,Alert al){
        this();
        this.al=al;
        this.c=c;
        DefaultListModel m = (DefaultListModel)(jList1.getModel());
        m.clear();
        String[] s=c.getDetailInfo().split("\n");
        for(int i=0; i<s.length; i++){
            m.addElement(s[i]);
        }
        jButton3.setEnabled(true);
    }
    
    public ResultsDetailGUI(int id){
        this();
        DefaultListModel m = (DefaultListModel)(jList1.getModel());
        m.clear();
        SearchResult result=TransSystem.getSearchResult(id); 
        String[] s=result.toString().split("\n");
        for(int i=0; i<s.length; i++){
            m.addElement(s[i]);
        }
        jButton3.setEnabled(false);
    }
    
    public ResultsDetailGUI(Carpool c){
        this();
        this.c=c;
        DefaultListModel m = (DefaultListModel)(jList1.getModel());
        m.clear();
        String[] s=c.getSearchDetailInfo().split("\n");
        for(int i=0; i<s.length; i++){
            m.addElement(s[i]);
        }
        jButton3.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Result Detail");

        jList1.setModel(new javax.swing.DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Set Alert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Join Carpool");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinCarpool(){
        if(TransSystem.getPlogin()==0){
            JOptionPane.showMessageDialog(null,"You need to login first");
            PassengerLoginGUI plgui=new PassengerLoginGUI();
            plgui.setVisible(true);
        }else{
            c.addPassenger(TransSystem.getP());
            JOptionPane.showMessageDialog(null,"have join the carpool now and the carpool provider name is "+c.getProvider().getPname());
        }
    }
    
    private void setAlert(){
        if(al!=null){
            if(c!=null){
                al.setActive(1);
                al.setAlertTime(c.getStartTime());
                JOptionPane.showMessageDialog(null,"Set Alert successfully and we will alert you at "+al.getAlertTime());
            }else{
                SearchResult result=TransSystem.getSearchResult(srid); 
                int wt=result.getD().calculateAlertWaitingTime(result.getBl().get(result.getBl().size()-1),al.getArriveTime());
                al.setActive(1);
                al.setAlertTime(al.getArriveTime().minusMinutes(wt));
                JOptionPane.showMessageDialog(null,"Set Alert successfully and we will alert you at "+al.getAlertTime());
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        joinCarpool();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setAlert();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsDetailGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsDetailGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
